# Site settings
title: K4GC | Bryan page
description: ""
url: "https://anpage.github.io/k4gc/" # TODO: Temporary
author:
  name: "Bryan Page"
  email: ""
  url: "http://k4gc.com/"

# Build settings
baseurl: /k4gc # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
